using System;
using System.Collections.Generic;
using System.Text;

namespace Altinn.Profile.Core.AddressVerifications.Models
{
    /// <summary>
    /// Represents a verification code used for address verification, including information about the user, code, expiration, and address type.
    /// </summary>
    public class VerificationCode
    {
        /// <summary>
        /// Gets or sets the user identifier associated with the verification code.
        /// </summary>
        public int UserId { get; set; }

        /// <summary>
        /// Gets or sets the unique identifier for the verification code. Generated by the database.
        /// </summary>
        public int VerificationCodeId { get; set; }

        /// <summary>
        /// Gets or sets the number of failed attempts to use the verification code.
        /// </summary>
        public int FailedAttempts { get; set; } = 0;

        /// <summary>
        /// Gets or sets the expiration date and time of the verification code.
        /// </summary>
        public DateTime Expires { get; set; }

        /// <summary>
        /// Gets or sets the creation date and time of the verification code.
        /// </summary>
        public DateTime Created { get; set; }

        /// <summary>
        /// Gets or sets the hash of the verification code.
        /// </summary>
        public string VerificationCodeHash { get; set; } = string.Empty;

        private string _address = string.Empty;

        /// <summary>
        /// Gets or sets the address (e.g., email or phone number) associated with the verification code.
        /// Setter always trims and converts the value to lower case.
        /// </summary>
        public string Address
        {
            get => _address;
            set => _address = (value ?? string.Empty).Trim().ToLower();
        }

        /// <summary>
        /// Gets or sets the type of address (e.g., Email or Sms) associated with the verification code.
        /// </summary>
        public AddressType AddressType { get; set; }
    }
}
