// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Altinn.Profile.Models
{
    /// <summary>
    /// Represents a mailbox supplier entity.
    /// </summary>
    [Table("mailbox_supplier", Schema = "contact_and_reservation")]
    public partial class MailboxSupplier
    {
        /// <summary>
        /// Gets or sets the unique identifier for the mailbox supplier.
        /// </summary>
        [Key]
        [Column("mailbox_supplier_id")]
        public int MailboxSupplierId { get; set; }

        /// <summary>
        /// Gets or sets the organization number.
        /// </summary>
        [Required]
        [Column("org_number_ak")]
        [StringLength(9)]
        public string OrgNumberAk { get; set; }

        /// <summary>
        /// Gets or sets the collection of registers associated with the mailbox supplier.
        /// </summary>
        [InverseProperty("MailboxSupplierIdFkNavigation")]
        public virtual ICollection<Register> Registers { get; set; } = new List<Register>();
    }
}
