version: '3.4'

networks:
  altinnplatform_network:
    external: false

services:
  altinn_platform_profile:
    container_name: altinn-platform-profile
    image: altinnplatformprofile:latest
    restart: always
    networks:
      - altinnplatform_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:5030
      - PostgreSqlSettings__AdminConnectionString=Host=host.docker.internal;Port=5432;Username=platform_profile_admin;Password={0};Database=profiledb
      - PostgreSqlSettings__ConnectionString=Host=host.docker.internal;Port=5432;Username=platform_profile;Password={0};Database=profiledb
    ports:
      - "5030:5030"
    build:
      context: .
      dockerfile: Dockerfile
