<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>eb6385ce-7ac9-489f-8f92-f4f469cd7e83</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.json" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.11" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="Npgsql.DependencyInjection" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <None Update="original_resourcelist.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="resourcelist.af-included.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="resourcelist.af-excluded.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
