// <auto-generated />
using System;
using Altinn.Profile.Integrations.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Altinn.Profile.Integrations.Migrations
{
    [DbContext(typeof(ProfileDbContext))]
    [Migration("20260604112029_AlterTableReceiptSettings")]
    partial class AlterTableReceiptSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Altinn.Profile.Core.AddressVerifications.Models.VerificationCode", b =>
                {
                    b.Property<int>("VerificationCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("verification_code_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("VerificationCodeId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address_type");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempts");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("VerificationCodeHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verification_code_hash");

                    b.HasKey("VerificationCodeId")
                        .HasName("verification_code_id_pkey");

                    b.HasIndex(new[] { "UserId", "Address", "AddressType" }, "ix_user_id_address_address_type")
                        .IsUnique()
                        .HasDatabaseName("ix_verification_codes_user_id_address_address_type");

                    b.ToTable("verification_codes", "address_verifications");
                });

            modelBuilder.Entity("Altinn.Profile.Core.AddressVerifications.Models.VerifiedAddress", b =>
                {
                    b.Property<int>("VerifiedAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("verified_address_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("VerifiedAddressId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address_type");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("VerifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("VerifiedAddressId")
                        .HasName("pk_verified_addresses");

                    b.HasIndex(new[] { "UserId", "Address", "AddressType" }, "ix_user_id_address_address_type")
                        .IsUnique()
                        .HasDatabaseName("ix_verified_addresses_user_id_address_address_type");

                    b.ToTable("verified_addresses", "address_verifications");
                });

            modelBuilder.Entity("Altinn.Profile.Core.ProfessionalNotificationAddresses.UserPartyContactInfo", b =>
                {
                    b.Property<long>("UserPartyContactInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_party_contact_info_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("UserPartyContactInfoId"));

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("email_address");

                    b.Property<DateTime>("LastChanged")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_changed");

                    b.Property<Guid>("PartyUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("party_uuid");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("phone_number");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("UserPartyContactInfoId")
                        .HasName("user_party_contact_info_pkey");

                    b.HasIndex(new[] { "EmailAddress" }, "ix_email_address")
                        .HasDatabaseName("ix_user_party_contact_info_email_address");

                    b.HasIndex(new[] { "PartyUuid", "UserId" }, "ix_user_party_contact_info_party_uuid_user_id")
                        .HasDatabaseName("ix_user_party_contact_info_party_uuid_user_id");

                    b.HasIndex(new[] { "PhoneNumber" }, "ix_user_party_contact_info_phone_number")
                        .HasDatabaseName("ix_user_party_contact_info_phone_number");

                    b.HasIndex(new[] { "UserId" }, "ix_user_party_contact_info_user_id")
                        .HasDatabaseName("ix_user_party_contact_info_user_id");

                    b.ToTable("user_party_contact_info", "professional_notification_settings");
                });

            modelBuilder.Entity("Altinn.Profile.Core.ProfessionalNotificationAddresses.UserPartyContactInfoResource", b =>
                {
                    b.Property<long>("UserPartyContactInfoResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_party_contact_info_resource_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("UserPartyContactInfoResourceId"));

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resource_id");

                    b.Property<long>("UserPartyContactInfoId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_party_contact_info_id");

                    b.HasKey("UserPartyContactInfoResourceId")
                        .HasName("user_party_contact_info_resource_pkey");

                    b.HasIndex("UserPartyContactInfoId")
                        .HasDatabaseName("ix_user_party_contact_info_resources_user_party_contact_info_id");

                    b.ToTable("user_party_contact_info_resources", "professional_notification_settings");
                });

            modelBuilder.Entity("Altinn.Profile.Core.User.ContactInfo.UserContactInfo", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("email_address");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("phone_number");

                    b.Property<DateTime?>("PhoneNumberLastChanged")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("phone_number_last_changed");

                    b.Property<Guid>("UserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("pk_self_identified_users");

                    b.ToTable("self_identified_users", "user_preferences");
                });

            modelBuilder.Entity("Altinn.Profile.Core.User.PartyGroups.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroupId"));

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean")
                        .HasColumnName("is_favorite");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("GroupId")
                        .HasName("group_id_pkey");

                    b.HasIndex(new[] { "UserId", "IsFavorite" }, "ix_user_favorite")
                        .IsUnique()
                        .HasDatabaseName("ix_groups_user_id_is_favorite")
                        .HasFilter("is_favorite = true");

                    b.HasIndex(new[] { "UserId" }, "ix_user_id")
                        .HasDatabaseName("ix_groups_user_id");

                    b.ToTable("groups", "user_preferences");
                });

            modelBuilder.Entity("Altinn.Profile.Core.User.PartyGroups.PartyGroupAssociation", b =>
                {
                    b.Property<int>("AssociationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("association_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssociationId"));

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<Guid>("PartyUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("party_uuid");

                    b.HasKey("AssociationId")
                        .HasName("association_id_pkey");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_party_group_association_group_id");

                    b.ToTable("party_group_association", "user_preferences");
                });

            modelBuilder.Entity("Altinn.Profile.Core.User.ProfileSettings.ProfileSettings", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<bool>("DoNotPromptForParty")
                        .HasColumnType("boolean")
                        .HasColumnName("do_not_prompt_for_party");

                    b.Property<DateTime?>("IgnoreUnitProfileDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ignore_unit_profile_date_time");

                    b.Property<string>("LanguageType")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("language_type");

                    b.Property<Guid?>("PreselectedPartyUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("preselected_party_uuid");

                    b.Property<bool>("ShouldShowDeletedEntities")
                        .HasColumnType("boolean")
                        .HasColumnName("should_show_deleted_entities");

                    b.Property<bool>("ShouldShowSubEntities")
                        .HasColumnType("boolean")
                        .HasColumnName("should_show_sub_entities");

                    b.Property<bool>("ShowClientUnits")
                        .HasColumnType("boolean")
                        .HasColumnName("show_client_units");

                    b.HasKey("UserId")
                        .HasName("user_id_pkey");

                    b.ToTable("profile_settings", "user_preferences");
                });

            modelBuilder.Entity("Altinn.Profile.Core.User.ReceiptSettings.ReceiptSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_private");

                    b.Property<bool?>("RequestReceipt")
                        .HasColumnType("boolean")
                        .HasColumnName("request_receipt");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<Guid>("UserUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_uuid");

                    b.HasKey("Id")
                        .HasName("id_pkey");

                    b.ToTable("receipt_settings", "user_preferences");
                });

            modelBuilder.Entity("Altinn.Profile.Integrations.Entities.ChangelogSyncMetadata", b =>
                {
                    b.Property<string>("LastChangedId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("last_changed_id");

                    b.Property<int>("DataType")
                        .HasColumnType("integer")
                        .HasColumnName("data_type");

                    b.Property<long>("LastChangeTicks")
                        .HasColumnType("bigint")
                        .HasColumnName("last_change_ticks");

                    b.HasKey("LastChangedId")
                        .HasName("changelog_sync_metadata_pkey");

                    b.ToTable("changelog_sync_metadata", "lease");
                });

            modelBuilder.Entity("Altinn.Profile.Integrations.Entities.MailboxSupplier", b =>
                {
                    b.Property<int>("MailboxSupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mailbox_supplier_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("MailboxSupplierId"));

                    b.Property<string>("OrgNumberAk")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character(9)")
                        .HasColumnName("org_number_ak")
                        .IsFixedLength();

                    b.HasKey("MailboxSupplierId")
                        .HasName("mailbox_supplier_pkey");

                    b.HasIndex(new[] { "OrgNumberAk" }, "ix_mailbox_supplier_org_number_ak")
                        .IsUnique()
                        .HasDatabaseName("ix_mailbox_supplier_org_number_ak");

                    b.ToTable("mailbox_supplier", "contact_and_reservation");
                });

            modelBuilder.Entity("Altinn.Profile.Integrations.Entities.Metadata", b =>
                {
                    b.Property<long>("LatestChangeNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("latest_change_number");

                    b.Property<DateTime?>("Exported")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exported");

                    b.HasKey("LatestChangeNumber")
                        .HasName("metadata_pkey");

                    b.ToTable("metadata", "contact_and_reservation");
                });

            modelBuilder.Entity("Altinn.Profile.Integrations.Entities.NotificationAddressDE", b =>
                {
                    b.Property<int>("NotificationAddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("notification_address_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationAddressID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<int>("AddressType")
                        .HasColumnType("integer")
                        .HasColumnName("address_type");

                    b.Property<DateTime>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date_time")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Domain")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("domain");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_address");

                    b.Property<bool?>("HasRegistryAccepted")
                        .HasColumnType("boolean")
                        .HasColumnName("has_registry_accepted");

                    b.Property<bool?>("IsSoftDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_soft_deleted");

                    b.Property<string>("NotificationName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("notification_name");

                    b.Property<string>("RegistryID")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("registry_id");

                    b.Property<int>("RegistryOrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("fk_registry_organization_id");

                    b.Property<DateTime?>("RegistryUpdatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registry_updated_date_time");

                    b.Property<int>("UpdateSource")
                        .HasColumnType("integer")
                        .HasColumnName("update_source");

                    b.HasKey("NotificationAddressID")
                        .HasName("contact_info_pkey");

                    b.HasIndex("RegistryID")
                        .IsUnique()
                        .HasDatabaseName("ix_notifications_address_registry_id");

                    b.HasIndex("RegistryOrganizationId")
                        .HasDatabaseName("ix_notifications_address_fk_registry_organization_id");

                    b.HasIndex(new[] { "FullAddress" }, "ix_notifications_address_full_address")
                        .HasDatabaseName("ix_notifications_address_full_address");

                    b.ToTable("notifications_address", "organization_notification_address");
                });

            modelBuilder.Entity("Altinn.Profile.Integrations.Entities.OrganizationDE", b =>
                {
                    b.Property<int>("RegistryOrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("registry_organization_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RegistryOrganizationId"));

                    b.Property<string>("RegistryOrganizationNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("registry_organization_number");

                    b.HasKey("RegistryOrganizationId")
                        .HasName("organization_id_pkey");

                    b.HasIndex("RegistryOrganizationNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_registry_organization_number");

                    b.ToTable("organizations", "organization_notification_address");
                });

            modelBuilder.Entity("Altinn.Profile.Integrations.Entities.Person", b =>
                {
                    b.Property<int>("ContactAndReservationUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("contact_and_reservation_user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ContactAndReservationUserId"));

                    b.Property<string>("Description")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("description");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("email_address");

                    b.Property<DateTime?>("EmailAddressLastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_address_last_updated");

                    b.Property<DateTime?>("EmailAddressLastVerified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_address_last_verified");

                    b.Property<string>("FnumberAk")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character(11)")
                        .HasColumnName("fnumber_ak")
                        .IsFixedLength();

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("language_code")
                        .IsFixedLength();

                    b.Property<string>("MailboxAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mailbox_address");

                    b.Property<int?>("MailboxSupplierIdFk")
                        .HasColumnType("integer")
                        .HasColumnName("mailbox_supplier_id_fk");

                    b.Property<string>("MobilePhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mobile_phone_number");

                    b.Property<DateTime?>("MobilePhoneNumberLastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mobile_phone_number_last_updated");

                    b.Property<DateTime?>("MobilePhoneNumberLastVerified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mobile_phone_number_last_verified");

                    b.Property<bool?>("Reservation")
                        .HasColumnType("boolean")
                        .HasColumnName("reservation");

                    b.Property<string>("X509Certificate")
                        .HasColumnType("text")
                        .HasColumnName("x509_certificate");

                    b.HasKey("ContactAndReservationUserId")
                        .HasName("person_pkey");

                    b.HasIndex("MailboxSupplierIdFk")
                        .HasDatabaseName("ix_person_mailbox_supplier_id_fk");

                    b.HasIndex(new[] { "FnumberAk" }, "ix_person_fnumber_ak")
                        .IsUnique()
                        .HasDatabaseName("ix_person_fnumber_ak");

                    b.ToTable("person", "contact_and_reservation");
                });

            modelBuilder.Entity("Altinn.Profile.Integrations.Entities.RegistrySyncMetadata", b =>
                {
                    b.Property<string>("LastChangedId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("last_changed_id");

                    b.Property<DateTime>("LastChangedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_changed_date_time");

                    b.HasKey("LastChangedId")
                        .HasName("registry_sync_metadata_pkey");

                    b.ToTable("registry_sync_metadata", "organization_notification_address");
                });

            modelBuilder.Entity("Altinn.Profile.Integrations.Leases.Lease", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("Acquired")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acquired");

                    b.Property<DateTimeOffset>("Expires")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires");

                    b.Property<DateTimeOffset?>("Released")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released");

                    b.Property<Guid>("Token")
                        .HasColumnType("uuid")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("lease_id_pkey");

                    b.HasIndex(new[] { "Id" }, "ix_lease_id")
                        .IsUnique()
                        .HasDatabaseName("ix_lease_id");

                    b.ToTable("lease", "lease");
                });

            modelBuilder.Entity("Altinn.Profile.Core.ProfessionalNotificationAddresses.UserPartyContactInfoResource", b =>
                {
                    b.HasOne("Altinn.Profile.Core.ProfessionalNotificationAddresses.UserPartyContactInfo", "UserPartyContactInfo")
                        .WithMany("UserPartyContactInfoResources")
                        .HasForeignKey("UserPartyContactInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_party_contact_info_id");

                    b.Navigation("UserPartyContactInfo");
                });

            modelBuilder.Entity("Altinn.Profile.Core.User.PartyGroups.PartyGroupAssociation", b =>
                {
                    b.HasOne("Altinn.Profile.Core.User.PartyGroups.Group", "Group")
                        .WithMany("Parties")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_id");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Altinn.Profile.Integrations.Entities.NotificationAddressDE", b =>
                {
                    b.HasOne("Altinn.Profile.Integrations.Entities.OrganizationDE", "Organization")
                        .WithMany("NotificationAddresses")
                        .HasForeignKey("RegistryOrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Altinn.Profile.Integrations.Entities.Person", b =>
                {
                    b.HasOne("Altinn.Profile.Integrations.Entities.MailboxSupplier", "MailboxSupplierIdFkNavigation")
                        .WithMany("People")
                        .HasForeignKey("MailboxSupplierIdFk")
                        .HasConstraintName("fk_mailbox_supplier");

                    b.Navigation("MailboxSupplierIdFkNavigation");
                });

            modelBuilder.Entity("Altinn.Profile.Core.ProfessionalNotificationAddresses.UserPartyContactInfo", b =>
                {
                    b.Navigation("UserPartyContactInfoResources");
                });

            modelBuilder.Entity("Altinn.Profile.Core.User.PartyGroups.Group", b =>
                {
                    b.Navigation("Parties");
                });

            modelBuilder.Entity("Altinn.Profile.Integrations.Entities.MailboxSupplier", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("Altinn.Profile.Integrations.Entities.OrganizationDE", b =>
                {
                    b.Navigation("NotificationAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
