-- Scrips generated by "dotnet ef migrations script --startup-project ../Altinn.Profile"

-- Create table Organizations
CREATE TABLE organization_notification_address.organizations (
    registry_organization_id integer GENERATED BY DEFAULT AS IDENTITY,
    registry_organization_number character varying(9) NOT NULL,
    CONSTRAINT organization_id_pkey PRIMARY KEY (registry_organization_id)
);

-- Create table RegistrySyncMetadata
CREATE TABLE organization_notification_address.registry_sync_metadata (
    last_changed_id character varying(32) NOT NULL,
    last_changed_date_time timestamp with time zone NOT NULL,
    CONSTRAINT registry_sync_metadata_pkey PRIMARY KEY (last_changed_id)
);

-- Create table NotificationsAddresses
CREATE TABLE organization_notification_address.notifications_address (
    notification_address_id integer GENERATED BY DEFAULT AS IDENTITY,
    registry_id character varying(32) NOT NULL,
    address_type integer NOT NULL,
    domain character varying(200) NOT NULL,
    address character varying(200) NOT NULL,
    full_address character varying(200) NOT NULL,
    created_date_time timestamp with time zone default (now() at time zone 'utc'),
    registry_updated_date_time timestamp with time zone,
    update_source integer NOT NULL,
    has_registry_accepted boolean,
    is_soft_deleted boolean,
    notification_name character varying(200),
    fk_registry_organization_id integer NOT NULL,
    CONSTRAINT contact_info_pkey PRIMARY KEY (notification_address_id),
    CONSTRAINT fk_organization_id FOREIGN KEY (fk_registry_organization_id) REFERENCES organization_notification_address.organizations (registry_organization_id)
);

CREATE INDEX ix_notifications_address_fk_registry_organization_id ON organization_notification_address.notifications_address (fk_registry_organization_id);

CREATE UNIQUE INDEX ix_organizations_registry_organization_number ON organization_notification_address.organizations (registry_organization_number);