CREATE TABLE user_preferences.portal_settings (
    user_id integer GENERATED BY DEFAULT AS IDENTITY,
    language_type integer NOT NULL,
    do_not_prompt_for_party boolean NOT NULL,
    preselected_party_uuid uuid,
    show_client_units boolean NOT NULL,
    should_show_sub_entities boolean NOT NULL,
    should_show_deleted_entities boolean NOT NULL,
    CONSTRAINT user_id_pkey PRIMARY KEY (user_id)
);

CREATE INDEX ix_user_party_contact_info_user_id ON professional_notification_settings.user_party_contact_info (user_id);
