// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using Microsoft.EntityFrameworkCore;

namespace Altinn.Profile.Integrations.Entities;

/// <summary>
/// Represents a mailbox supplier in the contact and reservation schema.
/// </summary>
[Table("mailbox_supplier", Schema = "contact_and_reservation")]
[Index("OrgNumberAk", Name = "unique_org_number_ak", IsUnique = true)]
public partial class MailboxSupplier
{
    /// <summary>
    /// Gets or sets the unique identifier for the mailbox supplier.
    /// </summary>
    [Key]
    [Column("mailbox_supplier_id")]
    public int MailboxSupplierId { get; set; }

    /// <summary>
    /// Gets or sets the organization number of the mailbox supplier.
    /// </summary>
    [Required]
    [Column("org_number_ak")]
    [StringLength(9)]
    public string OrgNumberAk { get; set; }

    /// <summary>
    /// Gets or sets the collection of people associated with the mailbox supplier.
    /// </summary>
    [InverseProperty("MailboxSupplierIdFkNavigation")]
    public virtual ICollection<Person> People { get; set; } = new List<Person>();
}
