// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Altinn.Profile.Integrations.Entities;

/// <summary>
/// Represents metadata in the contact and reservation schema.
/// </summary>
[Table("metadata", Schema = "contact_and_reservation")]
public partial class Metadata
{
    /// <summary>
    /// Gets or sets the latest change number.
    /// </summary>
    [Key]
    [Column("latest_change_number")]
    public long LatestChangeNumber { get; set; }

    /// <summary>
    /// Gets or sets the date and time when the metadata was exported.
    /// </summary>
    [Column("exported")]
    public DateTime? Exported { get; set; }
}
