// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Altinn.Profile.Models;

using Microsoft.EntityFrameworkCore;

namespace Altinn.Profile.Context;

/// <summary>
/// Represents the database context for the profile database.
/// </summary>
public partial class ProfileDbContext : DbContext
{
    /// <summary>
    /// Initializes a new instance of the <see cref="ProfileDbContext"/> class.
    /// </summary>
    /// <param name="options">The options to be used by a <see cref="DbContext"/>.</param>
    public ProfileDbContext(DbContextOptions<ProfileDbContext> options)
        : base(options)
    {
    }

    /// <summary>
    /// Gets or sets the <see cref="DbSet{MailboxSupplier}"/> representing the mailbox suppliers.
    /// </summary>
    public virtual DbSet<MailboxSupplier> MailboxSuppliers { get; set; }

    /// <summary>
    /// Gets or sets the <see cref="DbSet{Metadata}"/> representing the metadata.
    /// </summary>
    public virtual DbSet<Metadata> Metadata { get; set; }

    /// <summary>
    /// Gets or sets the <see cref="DbSet{Register}"/> representing the registers.
    /// </summary>
    public virtual DbSet<Register> Registers { get; set; }

    /// <summary>
    /// Configures the schema needed for the context.
    /// </summary>
    /// <param name="modelBuilder">The builder being used to construct the model for this context.</param>
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MailboxSupplier>(entity =>
        {
            entity.HasKey(e => e.MailboxSupplierId).HasName("mailbox_supplier_pkey");

            entity.Property(e => e.MailboxSupplierId).UseIdentityAlwaysColumn();
            entity.Property(e => e.OrgNumberAk).IsFixedLength();
        });

        modelBuilder.Entity<Metadata>(entity =>
        {
            entity.HasKey(e => e.LatestChangeNumber).HasName("metadata_pkey");

            entity.Property(e => e.LatestChangeNumber).ValueGeneratedNever();
        });

        modelBuilder.Entity<Register>(entity =>
        {
            entity.HasKey(e => e.ContactAndReservationUserId).HasName("register_pkey");

            entity.Property(e => e.ContactAndReservationUserId).UseIdentityAlwaysColumn();
            entity.Property(e => e.FnumberAk).IsFixedLength();
            entity.Property(e => e.LanguageCode).IsFixedLength();

            entity.HasOne(d => d.MailboxSupplierIdFkNavigation)
                  .WithMany(p => p.Registers)
                  .HasConstraintName("fk_mailbox_supplier");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    /// <summary>
    /// A partial method that can be used to configure the model further.
    /// </summary>
    /// <param name="modelBuilder">The builder being used to construct the model for this context.</param>
    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
