GRANT USAGE, CREATE ON SCHEMA wolverine TO platform_profile;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA wolverine TO platform_profile;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA wolverine TO platform_profile;

ALTER DEFAULT PRIVILEGES IN SCHEMA wolverine
GRANT ALL PRIVILEGES ON TABLES TO platform_profile;

ALTER DEFAULT PRIVILEGES IN SCHEMA wolverine
GRANT ALL PRIVILEGES ON SEQUENCES TO platform_profile;