// <auto-generated> This file was originally auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using Altinn.Profile.Integrations.Entities;

using Microsoft.EntityFrameworkCore;

namespace Altinn.Profile.Integrations.Persistence;

/// <summary>
/// Represents the database context for the profile database.
/// </summary>
public partial class ProfileDbContext : DbContext
{
    /// <summary>
    /// Initializes a new instance of the <see cref="ProfileDbContext"/> class.
    /// </summary>
    /// <param name="options">The options to be used by a <see cref="DbContext"/>.</param>
    public ProfileDbContext(DbContextOptions<ProfileDbContext> options)
        : base(options)
    {
    }

    /// <summary>
    /// Gets or sets the <see cref="DbSet{MailboxSupplier}"/> representing the mailbox suppliers.
    /// </summary>
    public virtual DbSet<MailboxSupplier> MailboxSuppliers { get; set; }

    /// <summary>
    /// Gets or sets the <see cref="DbSet{Metadata}"/> representing the metadata.
    /// </summary>
    public virtual DbSet<Metadata> Metadata { get; set; }

    /// <summary>
    /// Gets or sets the <see cref="DbSet{Person}"/> representing the people.
    /// </summary>
    public virtual DbSet<Person> People { get; set; }

    /// <summary>
    /// The <see cref="DbSet{OrganizationDE}"/> representing orgnumber and id.
    /// </summary>
    public virtual DbSet<OrganizationDE> Organizations { get; set; }

    /// <summary>
    /// The <see cref="DbSet{NotificationAddressesDE}"/> representing notification addresses for organizations.
    /// </summary>
    public virtual DbSet<NotificationAddressDE> NotificationAddresses { get; set; }

    /// <summary>
    /// The <see cref="DbSet{RegistrySyncMetadata}"/> timestamp for last brreg-sync.
    /// </summary>
    public virtual DbSet<RegistrySyncMetadata> RegistrySyncMetadata { get; set; }

    /// <summary>
    /// The <see cref="DbSet{Group}"/> representing a users organization of parties in a named group.
    /// </summary>
    public virtual DbSet<Group> Groups { get; set; }

    /// <summary>
    /// The <see cref="DbSet{PartyGroupAssociation}"/> representing the association of parties in groups.
    /// </summary>
    public virtual DbSet<PartyGroupAssociation> PartyGroupAssociations { get; set; }

    /// <summary>
    /// Configures the schema needed for the context.
    /// </summary>
    /// <param name="modelBuilder">The builder being used to construct the model for this context.</param>
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MailboxSupplier>(entity =>
        {
            entity.HasKey(e => e.MailboxSupplierId).HasName("mailbox_supplier_pkey");

            entity.Property(e => e.MailboxSupplierId).UseIdentityAlwaysColumn();
            entity.Property(e => e.OrgNumberAk).IsFixedLength();
        });

        modelBuilder.Entity<Metadata>(entity =>
        {
            entity.HasKey(e => e.LatestChangeNumber).HasName("metadata_pkey");

            entity.Property(e => e.LatestChangeNumber).ValueGeneratedNever();
        });

        modelBuilder.Entity<Person>(entity =>
        {
            entity.HasKey(e => e.ContactAndReservationUserId).HasName("person_pkey");

            entity.Property(e => e.ContactAndReservationUserId).UseIdentityAlwaysColumn();
            entity.Property(e => e.FnumberAk).IsFixedLength();
            entity.Property(e => e.LanguageCode).IsFixedLength();

            entity.HasOne(d => d.MailboxSupplierIdFkNavigation)
                  .WithMany(p => p.People)
                  .HasConstraintName("fk_mailbox_supplier");
        });

        modelBuilder.Entity<NotificationAddressDE>(entity =>
        {
            entity.HasKey(e => e.NotificationAddressID).HasName("contact_info_pkey");
            entity.Property(e => e.CreatedDateTime).HasDefaultValueSql("now()").ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<OrganizationDE>(entity =>
        {
            entity.HasKey(e => e.RegistryOrganizationId).HasName("organization_id_pkey");
            entity.HasMany(e => e.NotificationAddresses)
                    .WithOne(n => n.Organization)
                    .HasForeignKey(e => e.RegistryOrganizationId)
                    .HasConstraintName("fk_organization_id");
        });
        modelBuilder.Entity<RegistrySyncMetadata>(entity =>
        {
            entity.HasKey(e => e.LastChangedId).HasName("registry_sync_metadata_pkey");
        });

        modelBuilder.Entity<PartyGroupAssociation>(entity =>
        {
            entity.ToTable("party_group_association", "user_preferences");

            entity.HasKey(e => e.AssociationId).HasName("association_id_pkey");
            entity.Property(e => e.AssociationId).IsRequired();
            entity.Property(e => e.GroupId).IsRequired();
            entity.Property(e => e.PartyUuid).IsRequired();
            entity.Property(e => e.Created).HasDefaultValueSql("now()").ValueGeneratedOnAdd();

            entity.HasOne(d => d.Group)
                  .WithMany(p => p.Parties)
                  .HasForeignKey(d => d.GroupId)
                  .OnDelete(DeleteBehavior.Cascade)
                  .HasConstraintName("fk_group_id");
        });

        modelBuilder.Entity<Group>(entity =>
        {
            entity.ToTable("groups", "user_preferences");

            entity.HasKey(e => e.GroupId).HasName("group_id_pkey");
            entity.Property(e => e.GroupId).IsRequired();
            entity.Property(e => e.Name).IsRequired();
            entity.Property(e => e.UserId).IsRequired();

            entity.HasIndex(e => e.UserId, "ix_user_id");

            entity.HasMany(e => e.Parties)
                    .WithOne(n => n.Group)
                    .HasForeignKey(e => e.GroupId)
                    .HasConstraintName("fk_group_id");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    /// <summary>
    /// A partial method that can be used to configure the model further.
    /// </summary>
    /// <param name="modelBuilder">The builder being used to construct the model for this context.</param>
    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
